# Development Process State Machine Configuration
# Simplified workflow: waiting for job -> researching state

# All possible states in the development process
states:
  - waiting_for_job        # Initial state, waiting for job to be added via CLI
  - researching           # Deep research using research.sh script
  - completed             # Final state - research completed

# Events that trigger state transitions
events:
  - job_added             # Job added to database_queue via CLI
  - research_done         # Research completed successfully
  - error                 # Error occurred during processing

# State transitions define the workflow
transitions:
  # Job trigger
  - from: waiting_for_job
    to: researching
    event: job_added
    
  # Research completion
  - from: researching
    to: completed
    event: research_done
    
  # Error handling - can restart from waiting
  - from: "*"  # From any state
    to: waiting_for_job
    event: error

# Actions to execute in each state
actions:
  waiting_for_job:
    - type: check_database_queue
      description: "Checking for jobs in database queue"
      
  researching:
    - type: bash
      description: "Running research script with topic from database"
      command: "scripts/research.sh '{topic}' 'prompts/research_prompt.md' '{id}'"
      timeout: 300
      success: "research_done"
      error_mappings:
        "1": "error"
        "2": "error"
      
  completed:
    - type: database_record_action
      description: "Recording research completion"
      step_name: "research_completed"
      step_description: "Research phase completed successfully"

# Initial state
initial_state: waiting_for_job

# Configuration metadata
metadata:
  name: "Development Process State Machine"
  description: "Simplified workflow: waiting for job -> researching"
  version: "2.0.0"
  based_on: "Simplified research workflow with database queue integration"